### ISSUE TITLE
Requirements to run train

### ISSUE THREAD

**Issue by rrkarim** [kashyap7x/QuadNet#1]
Can you please share all the dependencies or the environment to run the training. I wasn't able to train the sparse conv nets because of segmentation error. I'm not what is the cause, it could be the bad installation of `sparseconvnet` or the difference between your pytorch version and mine.

**Comment by kashyap7x** [comment]
If I recall correctly, I had this problem when `sparseconvnet` gets compiled without GPU. You could try to run one of the [examples from that repository](https://github.com/facebookresearch/SparseConvNet/blob/master/examples/hello-world.py) that uses the GPU to see if this is the issue.

I was using a docker image for running my experiments set up with the following steps:
```
WORKDIR /workspace/
RUN git clone https://github.com/facebookresearch/SparseConvNet.git
COPY setup.py /workspace/SparseConvNet/
RUN cd SparseConvNet && bash build.sh && cd ..
ENV NUMBAPRO_CUDA_DRIVER /usr/lib/x86_64-linux-gnu/libcuda.so
ENV NUMBAPRO_NVVM /usr/local/cuda/nvvm/lib64/libnvvm.so
ENV NUMBAPRO_LIBDEVICE /usr/local/cuda/nvvm/libdevice


WORKDIR /workspace/
RUN git clone https://github.com/youansheng/torchcv.git
WORKDIR /workspace/torchcv/extensions/
RUN sh make.sh
```
