### ISSUE TITLE
Visualization for different levels

### ISSUE THREAD

**Issue by ShilinC** [kashyap7x/QuadNet#2]
Hello,

I tried your training and evaluation code. In your paper, you visualized Q5-Q0 (different levels in the quadtree), but the code only dump a single segmentation mask (see below). Can you share that part of the code or at least give me a hint on where to change in order to produce results of all levels?

Thanks!

![ADE_val_00000001](https://user-images.githubusercontent.com/11979931/96079135-da7dd780-0e68-11eb-82ee-5f71a18bf14c.png)

**Comment by kashyap7x** [comment]
Hello,

In the paper, we visualized Q5-Q0 for the ground truth segmentation masks - I believe these are available as the different entries of _out_map_ from the function _dense2quad_ in _gen_labels.py_
https://github.com/kashyap7x/QGN/blob/ee5399af269be2a54a5c33c9a949ebec3d5104dd/data_utils/gen_labels.py#L106

During training, these are also available in the data dictionary as output['seg_label_*'].

If you would like to visualize the different levels of the decoder output for a trained model, please modify the _forward()_ for the QGN decoder class.
https://github.com/kashyap7x/QGN/blob/ee5399af269be2a54a5c33c9a949ebec3d5104dd/models/models.py#L562

Currently, during inference, only the final segmentation is returned (_sum(quad_preds)_), however, the list _quad_preds_ before taking the sum should contain the predictions at different scales.

Hope this helps!

**Comment by ShilinC** [comment]
Thanks! I have successfully visualized the predictions at different scales by drawing all the quad_preds in the list.

**Comment by shahaamirbader** [comment]
Hi @ShilinC how were you able to visualize the scales? any help with the code will be appreciated.
